title: Sans fight
description: sans fight need helpers
template:
  repo: sans-fight-template
  name: sans-fight
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
